Added EXT-X-CUE-OUT and EXT-X-CUE-IN media segment tags
carlanton/m3u8-parser pull request #26
Opened 2020-09-08 12:24 UTC by JohanSpaedtke

Title says it all. Added the MediaSegmentTags
#EXT-X-CUE-OUT
#EXT-X-CUE-IN

2020-09-08 12:57 UTC, carlanton commented
Cool stuff! However, I believe that the correct type of cueOut() should be `Optional<Double>`?
Example: https://docs.aws.amazon.com/medialive/latest/ug/sample-manifests-hls.html

Also: make sure that your changes are formatted accordingly :)

2020-09-08 13:01 UTC, JohanSpaedtke commented
The more you know... The documentation I'm working from has it as an int but some googling also shows the following
#EXT-X-CUE-OUT:DURATION=30
Any idea how to support all of them in a sane way? 

Regarding formatting. Sure what did I do wrong :) ?

2020-09-09 07:15 UTC, carlanton commented
Ok, there seems to be multiple styles for ad markers. Let's use the format you proposed (Elemental style?). If someone need to support more styles, we can figure it out later :)

2020-09-09 07:16 UTC, JohanSpaedtke commented
Sure :) 
You had some issues with the formatting? What do you want med to fix?

2020-09-09 07:17 UTC, carlanton requested changes

2020-09-09 07:17 UTC, carlanton commented on src/main/java/io/lindstrom/m3u8/model/MediaSegment.java
> +    Optional<Integer> cueOut();
insert newline

2020-09-09 07:17 UTC, carlanton commented on src/main/java/io/lindstrom/m3u8/model/MediaSegment.java
> +    {
`{` should be on previous line

2020-09-09 07:17 UTC, carlanton commented on src/main/java/io/lindstrom/m3u8/parser/MediaSegmentTag.java
> +        public void read(MediaSegment.Builder builder, String attributes){
`){` should be `} {`

2020-09-09 07:46 UTC, carlanton approved these changes

2020-09-09 07:47 UTC, merged

2020-09-09 07:55 UTC, carlanton commented
Your change is included in version 0.15. It should be on maven soon :)